### ISSUE TITLE
Clear Logs Does Not Deallocate Memory

### ISSUE THREAD

**Issue by evenator** [swri-robotics/swri_console#11]
After running swri_console for an extended period of time, its memory footprint was up to 3.7 GB. I clicked Clear Logs, which removed all of the log messages from the display, but swri_console's memory use did not decrease.

**Comment by elliotjo** [comment]
I thought this might be some of the STL objects not releasing their internal storage when being cleared.  I changed the main suspects from using .clear() to .swap() with an empty temporary.  This does not resolve the problem.   I don't think it's a memory leak.  If I clear out the log with N messages, the memory usage won't start growing again until the log has grown back up to N messages.   So it's likely a case of the underlying STL allocator or malloc/free not releasing the memory back to the OS.  I'll look a little more into it to be sure it's not a memory leak.

**Comment by evenator** [comment]
I didn't test this rigorously (read:at all). I agree that it doesn't sound like a leak. If I get a chance to play with it, I'll let you know.
