### ISSUE TITLE
Release for All Distributions

### ISSUE THREAD

**Issue by evenator** [swri-robotics/swri_console#18]
Now that swri_console uses Qt5, it's time for a new release for ROS Indigo, Jade, and Kinetic

**Comment by evenator** [comment]
Note to self, this should be the 1.0.0 release.

**Comment by evenator** [comment]
@elliotjo Are there any other features you want to get in before I release 1.0.0? We're passing checks for Indigo, Jade, Kinetic, and Lunar, and the QT5 upgrade seems stable.

**Comment by elliotjo** [comment]
No, all the work I have pending is a major update that I shouldn't squeez in last minute.

**Comment by evenator** [comment]
Version 1.0 released for Indigo, Jade, Kinetic, and Lunar.
