### ISSUE TITLE
Feature: Set verbosity level of a node

### ISSUE THREAD

**Issue by Timple** [swri-robotics/swri_console#19]
It would be really nice if you could rightclick a rosnode on the left and a popup-menu appeared with the verbosity levels: 
* Debug
* Info
* etc

Because now you are able to display the debug messages, but by default they are not output by the node.

**Comment by pjreed** [comment]
Agreed, `rqt_logger_level` is a pain. I'll do this when I've got some free time if @elljotjo doesn't get to it first.

**Comment by pjreed** [comment]
Working on this in #20.

**Comment by pjreed** [comment]
Finally merged this in.
