### ISSUE TITLE
Save & restore user settings

### ISSUE THREAD

**Issue by elliotjo** [swri-robotics/swri_console#2]
As swri_console becomes more powerful and more customizable, it would make sense to save user settings and load them on startup so that users don't have to re-set everything every time it loads. The QSettings class provides a handy, platform-independent way of saving settings.

Things that should probably be saved:
Show Timestamps
Absolute Timestamps
Use regular expressions
Include filter
Exclude filter
Severity display selection
Follow Newest Messages
Font
There are other features that haven't been implemented yet (such as colorizing log messages) that should be saved, too.

**Comment by pjreed** [comment]
Oops, this should've been closed a while ago.
