### ISSUE TITLE
Add capability to load a rosout.log file 

### ISSUE THREAD

**Issue by philwesthart** [swri-robotics/swri_console#26]
Currently, swri_console can only read in bags that were previously saved from a different swri_console session. It would be nice if we could load logs from a ros session that didn't have swri_console running.

**Comment by elliotjo** [comment]
Just to clarify, swri_console can load any bag that contains a /rosout or /rosout_agg topic.  Bag files don't have to generated by previous swri_console session.

**Comment by philwesthart** [comment]
Thanks for the clarification.

**Comment by pjreed** [comment]
Completed in #27
