### ISSUE TITLE
Dashing no data

### ISSUE THREAD

**Issue by adamkrawczyk** [swri-robotics/swri_console#32]
I'm facing troubles with version for ros-dashing. Console opens but no data is received, nether using cyclonedds nor fastrtps. I can see only an empty window.

**Comment by pjreed** [comment]
Are you building from source or using the binary version?  Also, could you run `dpkg -l ros-dashing-rmw-cyclonedds-cpp` and check what version of CycloneDDS you have installed?  Prior to the most recent version (`0.5.1-1bionic.20200407.12`) it has a bug that prevented it from subscribing to `/rosout` properly.

You might also double-check what interface it's listening on when it starts; Cyclone should print out which interface it's using when it starts up, although I don't think FastRTPS does.  If it's choosing the wrong one, there's some instructions on manually setting Cyclone's configuration here: https://github.com/eclipse-cyclonedds/cyclonedds#configuration

As a simple test, you might try running one of the examples:
```bash
ros2 run examples_rclcpp_minimal_publisher publisher_lambda
```

That should log a line every time it publishes something; when I run that and swri_console in Dashing, both of them with `RMW_IMPLEMENTATION=rmw_cyclonedds_cpp` and a config file that uses my wired ethernet interface, I see an entry every time it publishes something.  You might also try running `ros2 topic echo /rosout` to see if you can see log messages on the console.

**Comment by adamkrawczyk** [comment]
I'm building cyclonedds from source so this is probably because of this bug. It's working today with fastrtps! I will check with different version of cyclonedds! 

Thank you for fast response.
