### ISSUE TITLE
Release for ROS2 foxy

### ISSUE THREAD

**Issue by Rayman** [swri-robotics/swri_console#34]
Hey,

Can you release this package for foxy. I'm running it from source for a couple of months and it works fine.

Thanks!

**Comment by Timple** [comment]
If this gets picked up, don't forget about `galactic` and `rolling` :slightly_smiling_face:.

**Comment by danthony06** [comment]
Should be out now for Foxy, Galactic, and Rolling. We're having some issues
transitioning to the ROS2 release process, but this should be done.

**Comment by Timple** [comment]
I can't find the galactic PR.
https://github.com/ros/rosdistro/pulls?q=is%3Apr+swri_console+is%3Aclosed

Was it overlooked?

**Comment by danthony06** [comment]
We're having some issues with different repositories getting released into ROS2. I'm working through this, and I've reopened the issue so that I make sure I don't lose track of it.

**Comment by tonynajjar** [comment]
Hi! Any news here?

**Comment by danthony06** [comment]
@Rayman and @tonynajjar sorry this took so long, I just ran the release process for Foxy, and will be doing it for Galactic and Humble shortly. You can see the Foxy process here: https://github.com/ros/rosdistro/pull/35185

**Comment by danthony06** [comment]
Okay, the PR for releasing into Foxy has been merged, and the Galactic and Humble PRs are submitted.

**Comment by tonynajjar** [comment]
Thanks!
