### ISSUE TITLE
[Feature] Absolute time option

### ISSUE THREAD

**Issue by mmoerdijk** [swri-robotics/swri_console#56]
Hi,

Thanks for making this debugging tool, I use it a lot!

I have a feature request, would it be possible to add an option to show the absolute time instead of the absolute timestamp?  I am not so good at parsing the Unix timestamp in my head, and I can imagine there are more people that have that problem.

If there is interest from your side but no time, I'm willing to give it a go myself.

**Comment by danthony06** [comment]
This was fixed in ROS1 with this PR: https://github.com/swri-robotics/swri_console/pull/57. I'm leaving the issue open so that we remember to add it to ROS2 as well.

**Comment by danthony06** [comment]
Closing this out. It's now in ROS2 as well.
