### ISSUE TITLE
Rolling release?

### ISSUE THREAD

**Issue by MatthijsBurgh** [swri-robotics/swri_console#59]
Could you create a rolling release?

**Comment by danthony06** [comment]
Sure thing, let me just check to make sure its working and I'll get it bloomed.

**Comment by danthony06** [comment]
Okay, we have previously released it. It looks like the build farm is building the source correctly, but failing to package it into binaries. I'm looking into what's causing this. The latest failed attempt at building binaries is here: https://build.ros2.org/job/Rbin_uJ64__swri_console__ubuntu_jammy_amd64__binary/233/console. I'm not sure why it's working on Iron and Humble but not Rolling.

**Comment by MatthijsBurgh** [comment]
I see you did figure it out, didn't you?

**Comment by danthony06** [comment]
The binaries built successfully for Rolling with the new update I did: https://build.ros2.org/job/Rbin_uJ64__swri_console__ubuntu_jammy_amd64__binary/234/. They should be available the next time OR does a sync. I'm going to close out this issue unless something else fails.
