### ISSUE TITLE
Prepare a Release

### ISSUE THREAD

**Issue by evenator** [swri-robotics/swri_console#9]
If there are any other issues/features that people want to finish before the first bloom release, comment below.

**Comment by elliotjo** [comment]
I'd like to to fix issues #4 and #5.  I can probably get to it this weekend.

**Comment by elliotjo** [comment]
Closed #4 and #5.  I'd also like to take a look at #8 tomorrow since that's bad behavior that users in the wild are likely to run into.

**Comment by elliotjo** [comment]
I fixed a few more issues.  I'm happy with the current state for an initial bloom.
